site_name: Documentação - Projeto GMP
theme:
  name: material
  favicon: assets/icontelebras_resized.ico
  logo: assets/logo.png
   palette:
                # Palette toggle for light mode
                - scheme: default
                  primary: light green
                  accent: green

                  toggle:
                          icon: material/brightness-7
                          name: Switch to dark mode

                # Palette toggle for dark mode
                - scheme: slate
                  primary: light green
                  accent: green

                  toggle:
                          icon: material/brightness-4
                          name: Switch to light mode
