name: ci
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install mkdocs-material
      - run: pip install mkdocs-glightbox
      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.BOT }}  # Substitua GH_TOKEN pelo nome do seu segredo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          mkdocs gh-deploy --force
